//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 4/19/2009 1:20:19 PM
namespace MvcApplication1.Models
{
    
    /// <summary>
    /// There are no comments for WidgetDBEntities in the schema.
    /// </summary>
    public partial class WidgetDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new WidgetDBEntities object using the connection string found in the 'WidgetDBEntities' section of the application configuration file.
        /// </summary>
        public WidgetDBEntities() : 
                base("name=WidgetDBEntities", "WidgetDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new WidgetDBEntities object.
        /// </summary>
        public WidgetDBEntities(string connectionString) : 
                base(connectionString, "WidgetDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new WidgetDBEntities object.
        /// </summary>
        public WidgetDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "WidgetDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for WidgetSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Widget> WidgetSet
        {
            get
            {
                if ((this._WidgetSet == null))
                {
                    this._WidgetSet = base.CreateQuery<Widget>("[WidgetSet]");
                }
                return this._WidgetSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Widget> _WidgetSet;
        /// <summary>
        /// There are no comments for WidgetSet in the schema.
        /// </summary>
        public void AddToWidgetSet(Widget widget)
        {
            base.AddObject("WidgetSet", widget);
        }
    }
    /// <summary>
    /// There are no comments for MvcApplication1.Models.Widget in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MvcApplication1.Models", Name="Widget")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Widget : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Widget object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="price">Initial value of Price.</param>
        public static Widget CreateWidget(int id, string name, decimal price)
        {
            Widget widget = new Widget();
            widget.Id = id;
            widget.Name = name;
            widget.Price = price;
            return widget;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this.ReportPropertyChanging("Price");
                this._Price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Price");
                this.OnPriceChanged();
            }
        }
        private decimal _Price;
        partial void OnPriceChanging(decimal value);
        partial void OnPriceChanged();
    }
}
