//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 4/27/2009 7:54:23 PM
namespace MvcApplication1.Models
{
    
    /// <summary>
    /// There are no comments for GuestBookDBEntities in the schema.
    /// </summary>
    public partial class GuestBookDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new GuestBookDBEntities object using the connection string found in the 'GuestBookDBEntities' section of the application configuration file.
        /// </summary>
        public GuestBookDBEntities() : 
                base("name=GuestBookDBEntities", "GuestBookDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GuestBookDBEntities object.
        /// </summary>
        public GuestBookDBEntities(string connectionString) : 
                base(connectionString, "GuestBookDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GuestBookDBEntities object.
        /// </summary>
        public GuestBookDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "GuestBookDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for GuestSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Guest> GuestSet
        {
            get
            {
                if ((this._GuestSet == null))
                {
                    this._GuestSet = base.CreateQuery<Guest>("[GuestSet]");
                }
                return this._GuestSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Guest> _GuestSet;
        /// <summary>
        /// There are no comments for GuestSet in the schema.
        /// </summary>
        public void AddToGuestSet(Guest guest)
        {
            base.AddObject("GuestSet", guest);
        }
    }
    /// <summary>
    /// There are no comments for GuestBookDBModel.Guest in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GuestBookDBModel", Name="Guest")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Guest : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Guest object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="message">Initial value of Message.</param>
        public static Guest CreateGuest(int id, string name, string message)
        {
            Guest guest = new Guest();
            guest.Id = id;
            guest.Name = name;
            guest.Message = message;
            return guest;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Message in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this.ReportPropertyChanging("Message");
                this._Message = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Message");
                this.OnMessageChanged();
            }
        }
        private string _Message;
        partial void OnMessageChanging(string value);
        partial void OnMessageChanged();
    }
}
