//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 2/27/2009 2:18:53 PM
namespace MvcApplication1.Models
{
    
    /// <summary>
    /// There are no comments for CustomersDBEntities in the schema.
    /// </summary>
    public partial class CustomersDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CustomersDBEntities object using the connection string found in the 'CustomersDBEntities' section of the application configuration file.
        /// </summary>
        public CustomersDBEntities() : 
                base("name=CustomersDBEntities", "CustomersDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CustomersDBEntities object.
        /// </summary>
        public CustomersDBEntities(string connectionString) : 
                base(connectionString, "CustomersDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CustomersDBEntities object.
        /// </summary>
        public CustomersDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CustomersDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for CustomerSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Customer> CustomerSet
        {
            get
            {
                if ((this._CustomerSet == null))
                {
                    this._CustomerSet = base.CreateQuery<Customer>("[CustomerSet]");
                }
                return this._CustomerSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Customer> _CustomerSet;
        /// <summary>
        /// There are no comments for CustomerSet in the schema.
        /// </summary>
        public void AddToCustomerSet(Customer customer)
        {
            base.AddObject("CustomerSet", customer);
        }
    }
    /// <summary>
    /// There are no comments for Models.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Models", Name="Customer")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Customer : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="receiveNewsletter">Initial value of ReceiveNewsletter.</param>
        public static Customer CreateCustomer(int id, string firstName, string lastName, bool receiveNewsletter)
        {
            Customer customer = new Customer();
            customer.Id = id;
            customer.FirstName = firstName;
            customer.LastName = lastName;
            customer.ReceiveNewsletter = receiveNewsletter;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this.ReportPropertyChanging("FirstName");
                this._FirstName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FirstName");
                this.OnFirstNameChanged();
            }
        }
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this.ReportPropertyChanging("LastName");
                this._LastName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LastName");
                this.OnLastNameChanged();
            }
        }
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Profile in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Profile
        {
            get
            {
                return this._Profile;
            }
            set
            {
                this.OnProfileChanging(value);
                this.ReportPropertyChanging("Profile");
                this._Profile = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Profile");
                this.OnProfileChanged();
            }
        }
        private string _Profile;
        partial void OnProfileChanging(string value);
        partial void OnProfileChanged();
        /// <summary>
        /// There are no comments for Property ReceiveNewsletter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReceiveNewsletter
        {
            get
            {
                return this._ReceiveNewsletter;
            }
            set
            {
                this.OnReceiveNewsletterChanging(value);
                this.ReportPropertyChanging("ReceiveNewsletter");
                this._ReceiveNewsletter = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReceiveNewsletter");
                this.OnReceiveNewsletterChanged();
            }
        }
        private bool _ReceiveNewsletter;
        partial void OnReceiveNewsletterChanging(bool value);
        partial void OnReceiveNewsletterChanged();
    }
}
