'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("ec32225f-d636-44de-8567-df8b1a5a1205")> 

'Original file name:
'Generation date: 4/21/2009 2:44:26 PM
'''<summary>
'''There are no comments for WidgetDBEntities in the schema.
'''</summary>
Partial Public Class WidgetDBEntities
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new WidgetDBEntities object using the connection string found in the 'WidgetDBEntities' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=WidgetDBEntities", "WidgetDBEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new WidgetDBEntities object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "WidgetDBEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new WidgetDBEntities object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "WidgetDBEntities")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for WidgetSet in the schema.
    '''</summary>
    Public ReadOnly Property WidgetSet() As Global.System.Data.Objects.ObjectQuery(Of Widget)
        Get
            If (Me._WidgetSet Is Nothing) Then
                Me._WidgetSet = MyBase.CreateQuery(Of Widget)("[WidgetSet]")
            End If
            Return Me._WidgetSet
        End Get
    End Property
    Private _WidgetSet As Global.System.Data.Objects.ObjectQuery(Of Widget)
    '''<summary>
    '''There are no comments for WidgetSet in the schema.
    '''</summary>
    Public Sub AddToWidgetSet(ByVal widget As Widget)
        MyBase.AddObject("WidgetSet", widget)
    End Sub
End Class
'''<summary>
'''There are no comments for MvcApplication1.Models.Widget in the schema.
'''</summary>
'''<KeyProperties>
'''Id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="MvcApplication1.Models", Name:="Widget"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Widget
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Widget object.
    '''</summary>
    '''<param name="id">Initial value of Id.</param>
    '''<param name="name">Initial value of Name.</param>
    '''<param name="price">Initial value of Price.</param>
    Public Shared Function CreateWidget(ByVal id As Integer, ByVal name As String, ByVal price As Decimal) As Widget
        Dim widget As Widget = New Widget
        widget.Id = id
        widget.Name = name
        widget.Price = price
        Return widget
    End Function
    '''<summary>
    '''There are no comments for Property Id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Id() As Integer
        Get
            Return Me._Id
        End Get
        Set
            Me.OnIdChanging(value)
            Me.ReportPropertyChanging("Id")
            Me._Id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Id")
            Me.OnIdChanged
        End Set
    End Property
    Private _Id As Integer
    Partial Private Sub OnIdChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIdChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Name in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Name() As String
        Get
            Return Me._Name
        End Get
        Set
            Me.OnNameChanging(value)
            Me.ReportPropertyChanging("Name")
            Me._Name = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Name")
            Me.OnNameChanged
        End Set
    End Property
    Private _Name As String
    Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Price in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Price() As Decimal
        Get
            Return Me._Price
        End Get
        Set
            Me.OnPriceChanging(value)
            Me.ReportPropertyChanging("Price")
            Me._Price = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Price")
            Me.OnPriceChanged
        End Set
    End Property
    Private _Price As Decimal
    Partial Private Sub OnPriceChanging(ByVal value As Decimal)
        End Sub
    Partial Private Sub OnPriceChanged()
        End Sub
End Class
