'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("b6f4e517-4a7f-4c08-a6d1-e60209cb6c04")> 

'Original file name:
'Generation date: 4/28/2009 6:49:06 PM
'''<summary>
'''There are no comments for GuestBookDBEntities in the schema.
'''</summary>
Partial Public Class GuestBookDBEntities
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new GuestBookDBEntities object using the connection string found in the 'GuestBookDBEntities' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=GuestBookDBEntities", "GuestBookDBEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new GuestBookDBEntities object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "GuestBookDBEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new GuestBookDBEntities object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "GuestBookDBEntities")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for GuestSet in the schema.
    '''</summary>
    Public ReadOnly Property GuestSet() As Global.System.Data.Objects.ObjectQuery(Of Guest)
        Get
            If (Me._GuestSet Is Nothing) Then
                Me._GuestSet = MyBase.CreateQuery(Of Guest)("[GuestSet]")
            End If
            Return Me._GuestSet
        End Get
    End Property
    Private _GuestSet As Global.System.Data.Objects.ObjectQuery(Of Guest)
    '''<summary>
    '''There are no comments for GuestSet in the schema.
    '''</summary>
    Public Sub AddToGuestSet(ByVal guest As Guest)
        MyBase.AddObject("GuestSet", guest)
    End Sub
End Class
'''<summary>
'''There are no comments for MvcApplication1.Models.Guest in the schema.
'''</summary>
'''<KeyProperties>
'''Id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="MvcApplication1.Models", Name:="Guest"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Guest
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Guest object.
    '''</summary>
    '''<param name="id">Initial value of Id.</param>
    '''<param name="name">Initial value of Name.</param>
    '''<param name="message">Initial value of Message.</param>
    Public Shared Function CreateGuest(ByVal id As Integer, ByVal name As String, ByVal message As String) As Guest
        Dim guest As Guest = New Guest
        guest.Id = id
        guest.Name = name
        guest.Message = message
        Return guest
    End Function
    '''<summary>
    '''There are no comments for Property Id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Id() As Integer
        Get
            Return Me._Id
        End Get
        Set
            Me.OnIdChanging(value)
            Me.ReportPropertyChanging("Id")
            Me._Id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Id")
            Me.OnIdChanged
        End Set
    End Property
    Private _Id As Integer
    Partial Private Sub OnIdChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIdChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Name in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Name() As String
        Get
            Return Me._Name
        End Get
        Set
            Me.OnNameChanging(value)
            Me.ReportPropertyChanging("Name")
            Me._Name = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Name")
            Me.OnNameChanged
        End Set
    End Property
    Private _Name As String
    Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Message in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Message() As String
        Get
            Return Me._Message
        End Get
        Set
            Me.OnMessageChanging(value)
            Me.ReportPropertyChanging("Message")
            Me._Message = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Message")
            Me.OnMessageChanged
        End Set
    End Property
    Private _Message As String
    Partial Private Sub OnMessageChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnMessageChanged()
        End Sub
End Class
